# ------------------------------
# General Data Splitting
# ------------------------------
train_test_split:
  test_size: 0.2
  random_state: 42

# ------------------------------
# GPU / Training Config
# ------------------------------
train:
  use_gpu: true
  fp16: true

# ------------------------------
# Random Forest Parameters
# ------------------------------
random_forest:
  n_estimators: 300
  max_depth: 20
  tfidf_max_features: 10000

# ------------------------------
# DistilBERT Training Parameters
# ------------------------------
distilbert:
  pretrained_model_name: "distilbert-base-uncased"
  epochs: 1
  batch_size: 4
  learning_rate: 2e-5
  warmup_steps: 500
  weight_decay: 0.01
  logging_steps: 100
  tokenizer_max_length: 256

# ------------------------------
# Feature Columns
# ------------------------------
features:
  selected:
    - clean_text
    - product_price
    - Rate
    - review_length
    - avg_word_length
  target: sentiment_encoded
